// All 66 books of the Holy Bible with metadata
export const BIBLE_BOOKS = [
  // Old Testament - 39 books
  { bookNumber: 1, bookName: "Genesis", testament: "Old Testament", abbreviation: "Gen", chapterCount: 50 },
  { bookNumber: 2, bookName: "Exodus", testament: "Old Testament", abbreviation: "Exo", chapterCount: 40 },
  { bookNumber: 3, bookName: "Leviticus", testament: "Old Testament", abbreviation: "Lev", chapterCount: 27 },
  { bookNumber: 4, bookName: "Numbers", testament: "Old Testament", abbreviation: "Num", chapterCount: 36 },
  { bookNumber: 5, bookName: "Deuteronomy", testament: "Old Testament", abbreviation: "Deu", chapterCount: 34 },
  { bookNumber: 6, bookName: "Joshua", testament: "Old Testament", abbreviation: "Jos", chapterCount: 24 },
  { bookNumber: 7, bookName: "Judges", testament: "Old Testament", abbreviation: "Jdg", chapterCount: 21 },
  { bookNumber: 8, bookName: "Ruth", testament: "Old Testament", abbreviation: "Rut", chapterCount: 4 },
  { bookNumber: 9, bookName: "1 Samuel", testament: "Old Testament", abbreviation: "1Sa", chapterCount: 31 },
  { bookNumber: 10, bookName: "2 Samuel", testament: "Old Testament", abbreviation: "2Sa", chapterCount: 24 },
  { bookNumber: 11, bookName: "1 Kings", testament: "Old Testament", abbreviation: "1Ki", chapterCount: 22 },
  { bookNumber: 12, bookName: "2 Kings", testament: "Old Testament", abbreviation: "2Ki", chapterCount: 25 },
  { bookNumber: 13, bookName: "1 Chronicles", testament: "Old Testament", abbreviation: "1Ch", chapterCount: 29 },
  { bookNumber: 14, bookName: "2 Chronicles", testament: "Old Testament", abbreviation: "2Ch", chapterCount: 36 },
  { bookNumber: 15, bookName: "Ezra", testament: "Old Testament", abbreviation: "Ezr", chapterCount: 10 },
  { bookNumber: 16, bookName: "Nehemiah", testament: "Old Testament", abbreviation: "Neh", chapterCount: 13 },
  { bookNumber: 17, bookName: "Esther", testament: "Old Testament", abbreviation: "Est", chapterCount: 10 },
  { bookNumber: 18, bookName: "Job", testament: "Old Testament", abbreviation: "Job", chapterCount: 42 },
  { bookNumber: 19, bookName: "Psalms", testament: "Old Testament", abbreviation: "Psa", chapterCount: 150 },
  { bookNumber: 20, bookName: "Proverbs", testament: "Old Testament", abbreviation: "Pro", chapterCount: 31 },
  { bookNumber: 21, bookName: "Ecclesiastes", testament: "Old Testament", abbreviation: "Ecc", chapterCount: 12 },
  { bookNumber: 22, bookName: "Song of Solomon", testament: "Old Testament", abbreviation: "Son", chapterCount: 8 },
  { bookNumber: 23, bookName: "Isaiah", testament: "Old Testament", abbreviation: "Isa", chapterCount: 66 },
  { bookNumber: 24, bookName: "Jeremiah", testament: "Old Testament", abbreviation: "Jer", chapterCount: 52 },
  { bookNumber: 25, bookName: "Lamentations", testament: "Old Testament", abbreviation: "Lam", chapterCount: 5 },
  { bookNumber: 26, bookName: "Ezekiel", testament: "Old Testament", abbreviation: "Eze", chapterCount: 48 },
  { bookNumber: 27, bookName: "Daniel", testament: "Old Testament", abbreviation: "Dan", chapterCount: 12 },
  { bookNumber: 28, bookName: "Hosea", testament: "Old Testament", abbreviation: "Hos", chapterCount: 14 },
  { bookNumber: 29, bookName: "Joel", testament: "Old Testament", abbreviation: "Joe", chapterCount: 3 },
  { bookNumber: 30, bookName: "Amos", testament: "Old Testament", abbreviation: "Amo", chapterCount: 9 },
  { bookNumber: 31, bookName: "Obadiah", testament: "Old Testament", abbreviation: "Oba", chapterCount: 1 },
  { bookNumber: 32, bookName: "Jonah", testament: "Old Testament", abbreviation: "Jon", chapterCount: 4 },
  { bookNumber: 33, bookName: "Micah", testament: "Old Testament", abbreviation: "Mic", chapterCount: 7 },
  { bookNumber: 34, bookName: "Nahum", testament: "Old Testament", abbreviation: "Nah", chapterCount: 3 },
  { bookNumber: 35, bookName: "Habakkuk", testament: "Old Testament", abbreviation: "Hab", chapterCount: 3 },
  { bookNumber: 36, bookName: "Zephaniah", testament: "Old Testament", abbreviation: "Zep", chapterCount: 3 },
  { bookNumber: 37, bookName: "Haggai", testament: "Old Testament", abbreviation: "Hag", chapterCount: 2 },
  { bookNumber: 38, bookName: "Zechariah", testament: "Old Testament", abbreviation: "Zec", chapterCount: 14 },
  { bookNumber: 39, bookName: "Malachi", testament: "Old Testament", abbreviation: "Mal", chapterCount: 4 },
  
  // New Testament - 27 books
  { bookNumber: 40, bookName: "Matthew", testament: "New Testament", abbreviation: "Mat", chapterCount: 28 },
  { bookNumber: 41, bookName: "Mark", testament: "New Testament", abbreviation: "Mar", chapterCount: 16 },
  { bookNumber: 42, bookName: "Luke", testament: "New Testament", abbreviation: "Luk", chapterCount: 24 },
  { bookNumber: 43, bookName: "John", testament: "New Testament", abbreviation: "Joh", chapterCount: 21 },
  { bookNumber: 44, bookName: "Acts", testament: "New Testament", abbreviation: "Act", chapterCount: 28 },
  { bookNumber: 45, bookName: "Romans", testament: "New Testament", abbreviation: "Rom", chapterCount: 16 },
  { bookNumber: 46, bookName: "1 Corinthians", testament: "New Testament", abbreviation: "1Co", chapterCount: 16 },
  { bookNumber: 47, bookName: "2 Corinthians", testament: "New Testament", abbreviation: "2Co", chapterCount: 13 },
  { bookNumber: 48, bookName: "Galatians", testament: "New Testament", abbreviation: "Gal", chapterCount: 6 },
  { bookNumber: 49, bookName: "Ephesians", testament: "New Testament", abbreviation: "Eph", chapterCount: 6 },
  { bookNumber: 50, bookName: "Philippians", testament: "New Testament", abbreviation: "Phi", chapterCount: 4 },
  { bookNumber: 51, bookName: "Colossians", testament: "New Testament", abbreviation: "Col", chapterCount: 4 },
  { bookNumber: 52, bookName: "1 Thessalonians", testament: "New Testament", abbreviation: "1Th", chapterCount: 5 },
  { bookNumber: 53, bookName: "2 Thessalonians", testament: "New Testament", abbreviation: "2Th", chapterCount: 3 },
  { bookNumber: 54, bookName: "1 Timothy", testament: "New Testament", abbreviation: "1Ti", chapterCount: 6 },
  { bookNumber: 55, bookName: "2 Timothy", testament: "New Testament", abbreviation: "2Ti", chapterCount: 4 },
  { bookNumber: 56, bookName: "Titus", testament: "New Testament", abbreviation: "Tit", chapterCount: 3 },
  { bookNumber: 57, bookName: "Philemon", testament: "New Testament", abbreviation: "Phm", chapterCount: 1 },
  { bookNumber: 58, bookName: "Hebrews", testament: "New Testament", abbreviation: "Heb", chapterCount: 13 },
  { bookNumber: 59, bookName: "James", testament: "New Testament", abbreviation: "Jas", chapterCount: 5 },
  { bookNumber: 60, bookName: "1 Peter", testament: "New Testament", abbreviation: "1Pe", chapterCount: 5 },
  { bookNumber: 61, bookName: "2 Peter", testament: "New Testament", abbreviation: "2Pe", chapterCount: 3 },
  { bookNumber: 62, bookName: "1 John", testament: "New Testament", abbreviation: "1Jo", chapterCount: 5 },
  { bookNumber: 63, bookName: "2 John", testament: "New Testament", abbreviation: "2Jo", chapterCount: 1 },
  { bookNumber: 64, bookName: "3 John", testament: "New Testament", abbreviation: "3Jo", chapterCount: 1 },
  { bookNumber: 65, bookName: "Jude", testament: "New Testament", abbreviation: "Jud", chapterCount: 1 },
  { bookNumber: 66, bookName: "Revelation", testament: "New Testament", abbreviation: "Rev", chapterCount: 22 },
];
